// Figure seed list — 401 historically-significant deceased people not
// already present in the figures table. Consumed by `seedFigures.mjs`,
// which:
//   1. Fetches each figure's Commons image URL from the Wikipedia REST
//      API at run time (avoids inventing URLs).
//   2. Upserts the row into Supabase using the service role key.
//
// Focal coordinates default to (0.5, 0.35) — typical for head-and-
// shoulders portraits where the face sits slightly above center. Tune
// individual figures by hand later.
//
// `wikipediaTitle` is supplied only when the article title differs from
// `name` (disambiguation pages, formal titles, etc.). Otherwise the
// seed script derives the title from `name` and lets the REST API's
// redirect handling do the work.

const SEED = [
  // ==========================================================================
  // EASY — household names (~200)
  // ==========================================================================

  // --- Scientists & inventors (35) ---
  { id: 'stephen-hawking', name: 'Stephen Hawking', aliases: ['hawking'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'carl-sagan', name: 'Carl Sagan', aliases: ['sagan'], difficulty: 'easy', era: '20th century', field: 'Astronomy', region: 'USA' },
  { id: 'louis-pasteur', name: 'Louis Pasteur', aliases: ['pasteur'], difficulty: 'easy', era: '19th century', field: 'Microbiology', region: 'France' },
  { id: 'gregor-mendel', name: 'Gregor Mendel', aliases: ['mendel'], difficulty: 'easy', era: '19th century', field: 'Genetics', region: 'Austria' },
  { id: 'michael-faraday', name: 'Michael Faraday', aliases: ['faraday'], difficulty: 'easy', era: '19th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'niels-bohr', name: 'Niels Bohr', aliases: ['bohr'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Denmark' },
  { id: 'werner-heisenberg', name: 'Werner Heisenberg', aliases: ['heisenberg'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Germany' },
  { id: 'max-planck', name: 'Max Planck', aliases: ['planck'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Germany' },
  { id: 'erwin-schrodinger', name: 'Erwin Schrödinger', aliases: ['schrodinger', 'schrödinger'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Austria' },
  { id: 'ernest-rutherford', name: 'Ernest Rutherford', aliases: ['rutherford'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'New Zealand / UK' },
  { id: 'alexander-fleming', name: 'Alexander Fleming', aliases: ['fleming'], difficulty: 'easy', era: '20th century', field: 'Medicine', region: 'United Kingdom' },
  { id: 'jonas-salk', name: 'Jonas Salk', aliases: ['salk'], difficulty: 'easy', era: '20th century', field: 'Medicine', region: 'USA' },
  { id: 'dmitri-mendeleev', name: 'Dmitri Mendeleev', aliases: ['mendeleev'], difficulty: 'easy', era: '19th century', field: 'Chemistry', region: 'Russia' },
  { id: 'alexander-graham-bell', name: 'Alexander Graham Bell', aliases: ['graham bell', 'bell'], difficulty: 'easy', era: '19th century', field: 'Invention', region: 'Scotland / USA' },
  { id: 'wright-brothers', name: 'Wright brothers', aliases: ['wright brothers'], wikipediaTitle: 'Wright brothers', difficulty: 'easy', era: '20th century', field: 'Aviation', region: 'USA' },
  { id: 'enrico-fermi', name: 'Enrico Fermi', aliases: ['fermi'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Italy / USA' },
  { id: 'robert-oppenheimer', name: 'J. Robert Oppenheimer', aliases: ['oppenheimer'], wikipediaTitle: 'J. Robert Oppenheimer', difficulty: 'easy', era: '20th century', field: 'Physics', region: 'USA' },
  { id: 'ada-lovelace', name: 'Ada Lovelace', aliases: ['lovelace'], difficulty: 'easy', era: '19th century', field: 'Computing', region: 'United Kingdom' },
  { id: 'alan-turing', name: 'Alan Turing', aliases: ['turing'], difficulty: 'easy', era: '20th century', field: 'Computing', region: 'United Kingdom' },
  { id: 'james-clerk-maxwell', name: 'James Clerk Maxwell', aliases: ['maxwell'], difficulty: 'easy', era: '19th century', field: 'Physics', region: 'Scotland' },
  { id: 'alessandro-volta', name: 'Alessandro Volta', aliases: ['volta'], difficulty: 'easy', era: '19th century', field: 'Physics', region: 'Italy' },
  { id: 'srinivasa-ramanujan', name: 'Srinivasa Ramanujan', aliases: ['ramanujan'], difficulty: 'easy', era: '20th century', field: 'Mathematics', region: 'India' },
  { id: 'linus-pauling', name: 'Linus Pauling', aliases: ['pauling'], difficulty: 'easy', era: '20th century', field: 'Chemistry', region: 'USA' },
  { id: 'francis-crick', name: 'Francis Crick', aliases: ['crick'], difficulty: 'easy', era: '20th century', field: 'Biology', region: 'United Kingdom' },
  { id: 'rosalind-franklin', name: 'Rosalind Franklin', aliases: ['franklin'], difficulty: 'easy', era: '20th century', field: 'Biology', region: 'United Kingdom' },
  { id: 'georg-ohm', name: 'Georg Ohm', aliases: ['ohm'], difficulty: 'easy', era: '19th century', field: 'Physics', region: 'Germany' },
  { id: 'andre-marie-ampere', name: 'André-Marie Ampère', aliases: ['ampere', 'ampère'], difficulty: 'easy', era: '19th century', field: 'Physics', region: 'France' },
  { id: 'paul-dirac', name: 'Paul Dirac', aliases: ['dirac'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'wolfgang-pauli', name: 'Wolfgang Pauli', aliases: ['pauli'], difficulty: 'easy', era: '20th century', field: 'Physics', region: 'Austria' },
  { id: 'antoine-lavoisier', name: 'Antoine Lavoisier', aliases: ['lavoisier'], difficulty: 'easy', era: '18th century', field: 'Chemistry', region: 'France' },
  { id: 'guglielmo-marconi', name: 'Guglielmo Marconi', aliases: ['marconi'], difficulty: 'easy', era: '20th century', field: 'Invention', region: 'Italy' },
  { id: 'samuel-morse', name: 'Samuel Morse', aliases: ['morse'], difficulty: 'easy', era: '19th century', field: 'Invention', region: 'USA' },
  { id: 'george-washington-carver', name: 'George Washington Carver', aliases: ['carver'], difficulty: 'easy', era: '20th century', field: 'Agriculture', region: 'USA' },
  { id: 'rudolf-diesel', name: 'Rudolf Diesel', aliases: ['diesel'], difficulty: 'easy', era: '19th century', field: 'Invention', region: 'Germany' },
  { id: 'rachel-carson', name: 'Rachel Carson', aliases: ['carson'], difficulty: 'easy', era: '20th century', field: 'Ecology', region: 'USA' },

  // --- Artists (25) ---
  { id: 'claude-monet', name: 'Claude Monet', aliases: ['monet'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'edouard-manet', name: 'Édouard Manet', aliases: ['manet'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'pierre-auguste-renoir', name: 'Pierre-Auguste Renoir', aliases: ['renoir'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'paul-cezanne', name: 'Paul Cézanne', aliases: ['cezanne', 'cézanne'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'edgar-degas', name: 'Edgar Degas', aliases: ['degas'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'rembrandt', name: 'Rembrandt', aliases: ['rembrandt van rijn'], difficulty: 'easy', era: '17th century', field: 'Painting', region: 'Netherlands' },
  { id: 'johannes-vermeer', name: 'Johannes Vermeer', aliases: ['vermeer'], difficulty: 'easy', era: '17th century', field: 'Painting', region: 'Netherlands' },
  { id: 'francisco-goya', name: 'Francisco Goya', aliases: ['goya'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'Spain' },
  { id: 'andy-warhol', name: 'Andy Warhol', aliases: ['warhol'], difficulty: 'easy', era: '20th century', field: 'Art', region: 'USA' },
  { id: 'salvador-dali', name: 'Salvador Dalí', aliases: ['dali', 'dalí'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Spain' },
  { id: 'rene-magritte', name: 'René Magritte', aliases: ['magritte'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Belgium' },
  { id: 'georgia-okeeffe', name: "Georgia O'Keeffe", aliases: ['okeeffe', "o'keeffe"], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'USA' },
  { id: 'henri-matisse', name: 'Henri Matisse', aliases: ['matisse'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'France' },
  { id: 'paul-gauguin', name: 'Paul Gauguin', aliases: ['gauguin'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'henri-de-toulouse-lautrec', name: 'Henri de Toulouse-Lautrec', aliases: ['toulouse-lautrec', 'lautrec'], difficulty: 'easy', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'edvard-munch', name: 'Edvard Munch', aliases: ['munch'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Norway' },
  { id: 'gustav-klimt', name: 'Gustav Klimt', aliases: ['klimt'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Austria' },
  { id: 'paul-klee', name: 'Paul Klee', aliases: ['klee'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Switzerland' },
  { id: 'wassily-kandinsky', name: 'Wassily Kandinsky', aliases: ['kandinsky'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'Russia' },
  { id: 'jackson-pollock', name: 'Jackson Pollock', aliases: ['pollock'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'USA' },
  { id: 'mark-rothko', name: 'Mark Rothko', aliases: ['rothko'], difficulty: 'easy', era: '20th century', field: 'Painting', region: 'USA' },
  { id: 'roy-lichtenstein', name: 'Roy Lichtenstein', aliases: ['lichtenstein'], difficulty: 'easy', era: '20th century', field: 'Art', region: 'USA' },
  { id: 'auguste-rodin', name: 'Auguste Rodin', aliases: ['rodin'], difficulty: 'easy', era: '20th century', field: 'Sculpture', region: 'France' },
  { id: 'alphonse-mucha', name: 'Alphonse Mucha', aliases: ['mucha'], difficulty: 'easy', era: '20th century', field: 'Art', region: 'Czech Republic' },
  { id: 'norman-rockwell', name: 'Norman Rockwell', aliases: ['rockwell'], difficulty: 'easy', era: '20th century', field: 'Illustration', region: 'USA' },

  // --- Composers & musicians (20) ---
  { id: 'johann-sebastian-bach', name: 'Johann Sebastian Bach', aliases: ['bach', 'js bach'], difficulty: 'easy', era: '18th century', field: 'Music', region: 'Germany' },
  { id: 'frederic-chopin', name: 'Frédéric Chopin', aliases: ['chopin'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Poland' },
  { id: 'richard-wagner', name: 'Richard Wagner', aliases: ['wagner'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Germany' },
  { id: 'antonio-vivaldi', name: 'Antonio Vivaldi', aliases: ['vivaldi'], difficulty: 'easy', era: '18th century', field: 'Music', region: 'Italy' },
  { id: 'franz-schubert', name: 'Franz Schubert', aliases: ['schubert'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Austria' },
  { id: 'johannes-brahms', name: 'Johannes Brahms', aliases: ['brahms'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Germany' },
  { id: 'george-frideric-handel', name: 'George Frideric Handel', aliases: ['handel'], difficulty: 'easy', era: '18th century', field: 'Music', region: 'Germany / UK' },
  { id: 'giuseppe-verdi', name: 'Giuseppe Verdi', aliases: ['verdi'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Italy' },
  { id: 'franz-liszt', name: 'Franz Liszt', aliases: ['liszt'], difficulty: 'easy', era: '19th century', field: 'Music', region: 'Hungary' },
  { id: 'igor-stravinsky', name: 'Igor Stravinsky', aliases: ['stravinsky'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'Russia' },
  { id: 'claude-debussy', name: 'Claude Debussy', aliases: ['debussy'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'France' },
  { id: 'gustav-mahler', name: 'Gustav Mahler', aliases: ['mahler'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'Austria' },
  { id: 'louis-armstrong', name: 'Louis Armstrong', aliases: ['satchmo'], difficulty: 'easy', era: '20th century', field: 'Jazz', region: 'USA' },
  { id: 'duke-ellington', name: 'Duke Ellington', aliases: ['ellington'], difficulty: 'easy', era: '20th century', field: 'Jazz', region: 'USA' },
  { id: 'ella-fitzgerald', name: 'Ella Fitzgerald', aliases: ['ella'], difficulty: 'easy', era: '20th century', field: 'Jazz', region: 'USA' },
  { id: 'billie-holiday', name: 'Billie Holiday', aliases: ['holiday'], difficulty: 'easy', era: '20th century', field: 'Jazz', region: 'USA' },
  { id: 'frank-sinatra', name: 'Frank Sinatra', aliases: ['sinatra'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'elvis-presley', name: 'Elvis Presley', aliases: ['elvis'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'john-lennon', name: 'John Lennon', aliases: ['lennon'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'United Kingdom' },
  { id: 'freddie-mercury', name: 'Freddie Mercury', aliases: ['mercury'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'United Kingdom' },

  // --- Writers (30) ---
  { id: 'edgar-allan-poe', name: 'Edgar Allan Poe', aliases: ['poe'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'USA' },
  { id: 'george-orwell', name: 'George Orwell', aliases: ['orwell'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'leo-tolstoy', name: 'Leo Tolstoy', aliases: ['tolstoy'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'Russia' },
  { id: 'jrr-tolkien', name: 'J. R. R. Tolkien', aliases: ['tolkien'], wikipediaTitle: 'J. R. R. Tolkien', difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'franz-kafka', name: 'Franz Kafka', aliases: ['kafka'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'Czech Republic' },
  { id: 'oscar-wilde', name: 'Oscar Wilde', aliases: ['wilde'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'Ireland' },
  { id: 'isaac-asimov', name: 'Isaac Asimov', aliases: ['asimov'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'ray-bradbury', name: 'Ray Bradbury', aliases: ['bradbury'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'robert-frost', name: 'Robert Frost', aliases: ['frost'], difficulty: 'easy', era: '20th century', field: 'Poetry', region: 'USA' },
  { id: 'wb-yeats', name: 'W. B. Yeats', aliases: ['yeats'], wikipediaTitle: 'W. B. Yeats', difficulty: 'easy', era: '20th century', field: 'Poetry', region: 'Ireland' },
  { id: 'walt-whitman', name: 'Walt Whitman', aliases: ['whitman'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'USA' },
  { id: 'ralph-waldo-emerson', name: 'Ralph Waldo Emerson', aliases: ['emerson'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'USA' },
  { id: 'henry-david-thoreau', name: 'Henry David Thoreau', aliases: ['thoreau'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'USA' },
  { id: 'emily-dickinson', name: 'Emily Dickinson', aliases: ['dickinson'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'USA' },
  { id: 'lord-byron', name: 'Lord Byron', aliases: ['byron'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'United Kingdom' },
  { id: 'percy-bysshe-shelley', name: 'Percy Bysshe Shelley', aliases: ['percy shelley'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'United Kingdom' },
  { id: 'john-keats', name: 'John Keats', aliases: ['keats'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'United Kingdom' },
  { id: 'william-wordsworth', name: 'William Wordsworth', aliases: ['wordsworth'], difficulty: 'easy', era: '19th century', field: 'Poetry', region: 'United Kingdom' },
  { id: 'charlotte-bronte', name: 'Charlotte Brontë', aliases: ['charlotte bronte'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'emily-bronte', name: 'Emily Brontë', aliases: ['emily bronte'], difficulty: 'easy', era: '19th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'agatha-christie', name: 'Agatha Christie', aliases: ['christie'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'arthur-conan-doyle', name: 'Arthur Conan Doyle', aliases: ['conan doyle', 'doyle'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'roald-dahl', name: 'Roald Dahl', aliases: ['dahl'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'cs-lewis', name: 'C. S. Lewis', aliases: ['cs lewis'], wikipediaTitle: 'C. S. Lewis', difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'aldous-huxley', name: 'Aldous Huxley', aliases: ['huxley'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'kurt-vonnegut', name: 'Kurt Vonnegut', aliases: ['vonnegut'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'truman-capote', name: 'Truman Capote', aliases: ['capote'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'john-steinbeck', name: 'John Steinbeck', aliases: ['steinbeck'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'f-scott-fitzgerald', name: 'F. Scott Fitzgerald', aliases: ['scott fitzgerald'], wikipediaTitle: 'F. Scott Fitzgerald', difficulty: 'easy', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'gabriel-garcia-marquez', name: 'Gabriel García Márquez', aliases: ['garcia marquez', 'márquez'], difficulty: 'easy', era: '20th century', field: 'Literature', region: 'Colombia' },

  // --- Leaders & political figures (30) ---
  { id: 'franklin-roosevelt', name: 'Franklin D. Roosevelt', aliases: ['fdr', 'franklin roosevelt'], wikipediaTitle: 'Franklin D. Roosevelt', difficulty: 'easy', era: '20th century', field: 'Politics', region: 'USA' },
  { id: 'theodore-roosevelt', name: 'Theodore Roosevelt', aliases: ['teddy roosevelt'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'USA' },
  { id: 'ronald-reagan', name: 'Ronald Reagan', aliases: ['reagan'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'USA' },
  { id: 'richard-nixon', name: 'Richard Nixon', aliases: ['nixon'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'USA' },
  { id: 'jimmy-carter', name: 'Jimmy Carter', aliases: ['carter'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'USA' },
  { id: 'ulysses-grant', name: 'Ulysses S. Grant', aliases: ['grant'], wikipediaTitle: 'Ulysses S. Grant', difficulty: 'easy', era: '19th century', field: 'Politics', region: 'USA' },
  { id: 'andrew-jackson', name: 'Andrew Jackson', aliases: ['andrew jackson'], difficulty: 'easy', era: '19th century', field: 'Politics', region: 'USA' },
  { id: 'james-madison', name: 'James Madison', aliases: ['madison'], difficulty: 'easy', era: '19th century', field: 'Politics', region: 'USA' },
  { id: 'john-adams', name: 'John Adams', aliases: ['john adams'], difficulty: 'easy', era: '18th century', field: 'Politics', region: 'USA' },
  { id: 'margaret-thatcher', name: 'Margaret Thatcher', aliases: ['thatcher'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'charles-de-gaulle', name: 'Charles de Gaulle', aliases: ['de gaulle'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'France' },
  { id: 'otto-von-bismarck', name: 'Otto von Bismarck', aliases: ['bismarck'], difficulty: 'easy', era: '19th century', field: 'Politics', region: 'Germany' },
  { id: 'joseph-stalin', name: 'Joseph Stalin', aliases: ['stalin'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Russia' },
  { id: 'vladimir-lenin', name: 'Vladimir Lenin', aliases: ['lenin'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Russia' },
  { id: 'leon-trotsky', name: 'Leon Trotsky', aliases: ['trotsky'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Russia' },
  { id: 'fidel-castro', name: 'Fidel Castro', aliases: ['castro'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Cuba' },
  { id: 'che-guevara', name: 'Che Guevara', aliases: ['che', 'guevara'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Argentina / Cuba' },
  { id: 'jose-de-san-martin', name: 'José de San Martín', aliases: ['san martin', 'san martín'], difficulty: 'easy', era: '19th century', field: 'Military', region: 'Argentina' },
  { id: 'emiliano-zapata', name: 'Emiliano Zapata', aliases: ['zapata'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Mexico' },
  { id: 'pancho-villa', name: 'Pancho Villa', aliases: ['villa'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Mexico' },
  { id: 'jawaharlal-nehru', name: 'Jawaharlal Nehru', aliases: ['nehru'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'India' },
  { id: 'indira-gandhi', name: 'Indira Gandhi', aliases: ['indira'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'India' },
  { id: 'lee-kuan-yew', name: 'Lee Kuan Yew', aliases: ['lee kuan yew'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Singapore' },
  { id: 'deng-xiaoping', name: 'Deng Xiaoping', aliases: ['deng'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'China' },
  { id: 'ho-chi-minh', name: 'Ho Chi Minh', aliases: ['ho chi minh'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Vietnam' },
  { id: 'kim-il-sung', name: 'Kim Il-sung', aliases: ['kim il sung'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'North Korea' },
  { id: 'gamal-abdel-nasser', name: 'Gamal Abdel Nasser', aliases: ['nasser'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Egypt' },
  { id: 'anwar-sadat', name: 'Anwar Sadat', aliases: ['sadat'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Egypt' },
  { id: 'yitzhak-rabin', name: 'Yitzhak Rabin', aliases: ['rabin'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Israel' },
  { id: 'golda-meir', name: 'Golda Meir', aliases: ['meir'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Israel' },

  // --- Royals & historical rulers (15) ---
  { id: 'queen-victoria', name: 'Queen Victoria', aliases: ['victoria'], difficulty: 'easy', era: '19th century', field: 'Royalty', region: 'United Kingdom' },
  { id: 'elizabeth-ii', name: 'Elizabeth II', aliases: ['queen elizabeth ii'], difficulty: 'easy', era: '20th century', field: 'Royalty', region: 'United Kingdom' },
  { id: 'marie-antoinette', name: 'Marie Antoinette', aliases: ['antoinette'], difficulty: 'easy', era: '18th century', field: 'Royalty', region: 'France' },
  { id: 'mary-queen-of-scots', name: 'Mary, Queen of Scots', aliases: ['mary stuart'], difficulty: 'easy', era: '16th century', field: 'Royalty', region: 'Scotland' },
  { id: 'henry-v', name: 'Henry V of England', aliases: ['henry v'], wikipediaTitle: 'Henry V of England', difficulty: 'easy', era: '15th century', field: 'Royalty', region: 'England' },
  { id: 'richard-iii', name: 'Richard III of England', aliases: ['richard iii'], wikipediaTitle: 'Richard III of England', difficulty: 'easy', era: '15th century', field: 'Royalty', region: 'England' },
  { id: 'william-the-conqueror', name: 'William the Conqueror', aliases: ['william i'], difficulty: 'easy', era: '11th century', field: 'Royalty', region: 'England' },
  { id: 'charlemagne', name: 'Charlemagne', aliases: ['charles the great'], difficulty: 'easy', era: '9th century', field: 'Royalty', region: 'Frankish Empire' },
  { id: 'ramesses-ii', name: 'Ramesses II', aliases: ['ramses ii', 'ramses the great'], difficulty: 'easy', era: 'Ancient', field: 'Royalty', region: 'Egypt' },
  { id: 'nefertiti', name: 'Nefertiti', aliases: ['nefertiti'], difficulty: 'easy', era: 'Ancient', field: 'Royalty', region: 'Egypt' },
  { id: 'akhenaten', name: 'Akhenaten', aliases: ['akhenaten'], difficulty: 'easy', era: 'Ancient', field: 'Royalty', region: 'Egypt' },
  { id: 'qin-shi-huang', name: 'Qin Shi Huang', aliases: ['qin shi huang'], difficulty: 'easy', era: 'Ancient', field: 'Royalty', region: 'China' },
  { id: 'shaka-zulu', name: 'Shaka', aliases: ['shaka zulu'], wikipediaTitle: 'Shaka', difficulty: 'easy', era: '19th century', field: 'Royalty', region: 'South Africa' },
  { id: 'moctezuma-ii', name: 'Moctezuma II', aliases: ['montezuma'], difficulty: 'easy', era: '16th century', field: 'Royalty', region: 'Aztec Empire' },
  { id: 'atahualpa', name: 'Atahualpa', aliases: ['atahualpa'], difficulty: 'easy', era: '16th century', field: 'Royalty', region: 'Inca Empire' },

  // --- Philosophers (10) ---
  { id: 'friedrich-nietzsche', name: 'Friedrich Nietzsche', aliases: ['nietzsche'], difficulty: 'easy', era: '19th century', field: 'Philosophy', region: 'Germany' },
  { id: 'hegel', name: 'Georg Wilhelm Friedrich Hegel', aliases: ['hegel'], wikipediaTitle: 'Georg Wilhelm Friedrich Hegel', difficulty: 'easy', era: '19th century', field: 'Philosophy', region: 'Germany' },
  { id: 'david-hume', name: 'David Hume', aliases: ['hume'], difficulty: 'easy', era: '18th century', field: 'Philosophy', region: 'Scotland' },
  { id: 'francis-bacon-philosopher', name: 'Francis Bacon', aliases: ['francis bacon'], wikipediaTitle: 'Francis Bacon', difficulty: 'easy', era: '17th century', field: 'Philosophy', region: 'United Kingdom' },
  { id: 'jean-paul-sartre', name: 'Jean-Paul Sartre', aliases: ['sartre'], difficulty: 'easy', era: '20th century', field: 'Philosophy', region: 'France' },
  { id: 'albert-camus', name: 'Albert Camus', aliases: ['camus'], difficulty: 'easy', era: '20th century', field: 'Philosophy', region: 'France' },
  { id: 'simone-de-beauvoir', name: 'Simone de Beauvoir', aliases: ['beauvoir'], difficulty: 'easy', era: '20th century', field: 'Philosophy', region: 'France' },
  { id: 'hannah-arendt', name: 'Hannah Arendt', aliases: ['arendt'], difficulty: 'easy', era: '20th century', field: 'Philosophy', region: 'Germany / USA' },
  { id: 'john-stuart-mill', name: 'John Stuart Mill', aliases: ['mill'], difficulty: 'easy', era: '19th century', field: 'Philosophy', region: 'United Kingdom' },
  { id: 'soren-kierkegaard', name: 'Søren Kierkegaard', aliases: ['kierkegaard'], difficulty: 'easy', era: '19th century', field: 'Philosophy', region: 'Denmark' },

  // --- Activists & reformers (15) ---
  { id: 'malcolm-x', name: 'Malcolm X', aliases: ['malcolm x'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'rosa-parks', name: 'Rosa Parks', aliases: ['rosa parks'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'helen-keller', name: 'Helen Keller', aliases: ['keller'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'cesar-chavez', name: 'César Chávez', aliases: ['chavez', 'cesar chavez'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'mary-mcleod-bethune', name: 'Mary McLeod Bethune', aliases: ['bethune'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'emmeline-pankhurst', name: 'Emmeline Pankhurst', aliases: ['pankhurst'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'United Kingdom' },
  { id: 'elizabeth-cady-stanton', name: 'Elizabeth Cady Stanton', aliases: ['cady stanton'], difficulty: 'easy', era: '19th century', field: 'Activism', region: 'USA' },
  { id: 'lucretia-mott', name: 'Lucretia Mott', aliases: ['mott'], difficulty: 'easy', era: '19th century', field: 'Activism', region: 'USA' },
  { id: 'william-wilberforce', name: 'William Wilberforce', aliases: ['wilberforce'], difficulty: 'easy', era: '19th century', field: 'Activism', region: 'United Kingdom' },
  { id: 'jane-addams', name: 'Jane Addams', aliases: ['addams'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'ida-b-wells', name: 'Ida B. Wells', aliases: ['ida wells'], wikipediaTitle: 'Ida B. Wells', difficulty: 'easy', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'desmond-tutu', name: 'Desmond Tutu', aliases: ['tutu'], difficulty: 'easy', era: '20th century', field: 'Activism', region: 'South Africa' },
  { id: 'aung-san', name: 'Aung San', aliases: ['aung san'], difficulty: 'easy', era: '20th century', field: 'Politics', region: 'Burma' },
  { id: 'eleanor-of-aquitaine', name: 'Eleanor of Aquitaine', aliases: ['eleanor of aquitaine'], difficulty: 'easy', era: '12th century', field: 'Royalty', region: 'France / England' },
  { id: 'thomas-paine', name: 'Thomas Paine', aliases: ['paine'], difficulty: 'easy', era: '18th century', field: 'Activism', region: 'USA / UK' },

  // --- Religious & spiritual (5) ---
  { id: 'gautama-buddha', name: 'Gautama Buddha', aliases: ['buddha'], difficulty: 'easy', era: 'Ancient', field: 'Religion', region: 'India / Nepal' },
  { id: 'augustine-of-hippo', name: 'Augustine of Hippo', aliases: ['saint augustine', 'st augustine'], difficulty: 'easy', era: 'Ancient', field: 'Religion', region: 'North Africa' },
  { id: 'francis-of-assisi', name: 'Francis of Assisi', aliases: ['saint francis', 'st francis'], difficulty: 'easy', era: '13th century', field: 'Religion', region: 'Italy' },
  { id: 'martin-luther', name: 'Martin Luther', aliases: ['luther'], difficulty: 'easy', era: '16th century', field: 'Religion', region: 'Germany' },
  { id: 'joseph-smith', name: 'Joseph Smith', aliases: ['joseph smith'], difficulty: 'easy', era: '19th century', field: 'Religion', region: 'USA' },

  // --- Pop culture icons (15) ---
  { id: 'marilyn-monroe', name: 'Marilyn Monroe', aliases: ['monroe'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'USA' },
  { id: 'james-dean', name: 'James Dean', aliases: ['james dean'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'USA' },
  { id: 'bob-marley', name: 'Bob Marley', aliases: ['marley'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'Jamaica' },
  { id: 'michael-jackson', name: 'Michael Jackson', aliases: ['mj'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'whitney-houston', name: 'Whitney Houston', aliases: ['whitney'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'david-bowie', name: 'David Bowie', aliases: ['bowie'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'United Kingdom' },
  { id: 'prince-musician', name: 'Prince', aliases: ['prince'], wikipediaTitle: 'Prince (musician)', difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'aretha-franklin', name: 'Aretha Franklin', aliases: ['aretha'], difficulty: 'easy', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'princess-diana', name: 'Diana, Princess of Wales', aliases: ['princess diana', 'lady di'], difficulty: 'easy', era: '20th century', field: 'Royalty', region: 'United Kingdom' },
  { id: 'audrey-hepburn', name: 'Audrey Hepburn', aliases: ['hepburn'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'United Kingdom' },
  { id: 'humphrey-bogart', name: 'Humphrey Bogart', aliases: ['bogart'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'USA' },
  { id: 'orson-welles', name: 'Orson Welles', aliases: ['welles'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'USA' },
  { id: 'alfred-hitchcock', name: 'Alfred Hitchcock', aliases: ['hitchcock'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'United Kingdom' },
  { id: 'steve-jobs', name: 'Steve Jobs', aliases: ['jobs'], difficulty: 'easy', era: '20th century', field: 'Technology', region: 'USA' },
  { id: 'bruce-lee', name: 'Bruce Lee', aliases: ['bruce lee'], difficulty: 'easy', era: '20th century', field: 'Film', region: 'Hong Kong / USA' },

  // ==========================================================================
  // MEDIUM — well-known with effort (~120)
  // ==========================================================================

  // --- Scientists (25) ---
  { id: 'robert-boyle', name: 'Robert Boyle', aliases: ['boyle'], difficulty: 'medium', era: '17th century', field: 'Chemistry', region: 'Ireland' },
  { id: 'john-dalton', name: 'John Dalton', aliases: ['dalton'], difficulty: 'medium', era: '19th century', field: 'Chemistry', region: 'United Kingdom' },
  { id: 'hermann-helmholtz', name: 'Hermann von Helmholtz', aliases: ['helmholtz'], difficulty: 'medium', era: '19th century', field: 'Physics', region: 'Germany' },
  { id: 'ludwig-boltzmann', name: 'Ludwig Boltzmann', aliases: ['boltzmann'], difficulty: 'medium', era: '19th century', field: 'Physics', region: 'Austria' },
  { id: 'john-von-neumann', name: 'John von Neumann', aliases: ['von neumann'], difficulty: 'medium', era: '20th century', field: 'Mathematics', region: 'Hungary / USA' },
  { id: 'carl-friedrich-gauss', name: 'Carl Friedrich Gauss', aliases: ['gauss'], difficulty: 'medium', era: '19th century', field: 'Mathematics', region: 'Germany' },
  { id: 'leonhard-euler', name: 'Leonhard Euler', aliases: ['euler'], difficulty: 'medium', era: '18th century', field: 'Mathematics', region: 'Switzerland' },
  { id: 'bernhard-riemann', name: 'Bernhard Riemann', aliases: ['riemann'], difficulty: 'medium', era: '19th century', field: 'Mathematics', region: 'Germany' },
  { id: 'joseph-fourier', name: 'Joseph Fourier', aliases: ['fourier'], difficulty: 'medium', era: '19th century', field: 'Mathematics', region: 'France' },
  { id: 'heinrich-hertz', name: 'Heinrich Hertz', aliases: ['hertz'], difficulty: 'medium', era: '19th century', field: 'Physics', region: 'Germany' },
  { id: 'lord-kelvin', name: 'William Thomson, 1st Baron Kelvin', aliases: ['kelvin', 'lord kelvin'], wikipediaTitle: 'William Thomson, 1st Baron Kelvin', difficulty: 'medium', era: '19th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'joseph-lister', name: 'Joseph Lister', aliases: ['lister'], difficulty: 'medium', era: '19th century', field: 'Medicine', region: 'United Kingdom' },
  { id: 'robert-koch', name: 'Robert Koch', aliases: ['koch'], difficulty: 'medium', era: '19th century', field: 'Microbiology', region: 'Germany' },
  { id: 'ignaz-semmelweis', name: 'Ignaz Semmelweis', aliases: ['semmelweis'], difficulty: 'medium', era: '19th century', field: 'Medicine', region: 'Hungary' },
  { id: 'rudolf-virchow', name: 'Rudolf Virchow', aliases: ['virchow'], difficulty: 'medium', era: '19th century', field: 'Medicine', region: 'Germany' },
  { id: 'claude-bernard', name: 'Claude Bernard', aliases: ['claude bernard'], difficulty: 'medium', era: '19th century', field: 'Physiology', region: 'France' },
  { id: 'edward-jenner', name: 'Edward Jenner', aliases: ['jenner'], difficulty: 'medium', era: '19th century', field: 'Medicine', region: 'United Kingdom' },
  { id: 'james-watt', name: 'James Watt', aliases: ['watt'], difficulty: 'medium', era: '18th century', field: 'Invention', region: 'Scotland' },
  { id: 'george-stephenson', name: 'George Stephenson', aliases: ['stephenson'], difficulty: 'medium', era: '19th century', field: 'Invention', region: 'United Kingdom' },
  { id: 'eli-whitney', name: 'Eli Whitney', aliases: ['whitney'], difficulty: 'medium', era: '19th century', field: 'Invention', region: 'USA' },
  { id: 'james-prescott-joule', name: 'James Prescott Joule', aliases: ['joule'], difficulty: 'medium', era: '19th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'lord-rayleigh', name: 'Lord Rayleigh', aliases: ['rayleigh'], wikipediaTitle: 'John William Strutt, 3rd Baron Rayleigh', difficulty: 'medium', era: '19th century', field: 'Physics', region: 'United Kingdom' },
  { id: 'edwin-hubble', name: 'Edwin Hubble', aliases: ['hubble'], difficulty: 'medium', era: '20th century', field: 'Astronomy', region: 'USA' },
  { id: 'richard-feynman', name: 'Richard Feynman', aliases: ['feynman'], difficulty: 'medium', era: '20th century', field: 'Physics', region: 'USA' },
  { id: 'lise-meitner', name: 'Lise Meitner', aliases: ['meitner'], difficulty: 'medium', era: '20th century', field: 'Physics', region: 'Austria / Sweden' },

  // --- Artists (15) ---
  { id: 'sandro-botticelli', name: 'Sandro Botticelli', aliases: ['botticelli'], difficulty: 'medium', era: '15th century', field: 'Painting', region: 'Italy' },
  { id: 'caravaggio', name: 'Caravaggio', aliases: ['caravaggio'], difficulty: 'medium', era: '17th century', field: 'Painting', region: 'Italy' },
  { id: 'titian', name: 'Titian', aliases: ['titian'], difficulty: 'medium', era: '16th century', field: 'Painting', region: 'Italy' },
  { id: 'el-greco', name: 'El Greco', aliases: ['el greco'], difficulty: 'medium', era: '17th century', field: 'Painting', region: 'Spain' },
  { id: 'diego-velazquez', name: 'Diego Velázquez', aliases: ['velazquez', 'velázquez'], difficulty: 'medium', era: '17th century', field: 'Painting', region: 'Spain' },
  { id: 'hieronymus-bosch', name: 'Hieronymus Bosch', aliases: ['bosch'], difficulty: 'medium', era: '16th century', field: 'Painting', region: 'Netherlands' },
  { id: 'pieter-bruegel', name: 'Pieter Bruegel the Elder', aliases: ['bruegel', 'brueghel'], difficulty: 'medium', era: '16th century', field: 'Painting', region: 'Netherlands' },
  { id: 'eugene-delacroix', name: 'Eugène Delacroix', aliases: ['delacroix'], difficulty: 'medium', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'jacques-louis-david', name: 'Jacques-Louis David', aliases: ['jacques-louis david'], difficulty: 'medium', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'gustave-courbet', name: 'Gustave Courbet', aliases: ['courbet'], difficulty: 'medium', era: '19th century', field: 'Painting', region: 'France' },
  { id: 'henri-rousseau-painter', name: 'Henri Rousseau', aliases: ['henri rousseau'], wikipediaTitle: 'Henri Rousseau', difficulty: 'medium', era: '20th century', field: 'Painting', region: 'France' },
  { id: 'amedeo-modigliani', name: 'Amedeo Modigliani', aliases: ['modigliani'], difficulty: 'medium', era: '20th century', field: 'Painting', region: 'Italy / France' },
  { id: 'marc-chagall', name: 'Marc Chagall', aliases: ['chagall'], difficulty: 'medium', era: '20th century', field: 'Painting', region: 'Russia / France' },
  { id: 'piet-mondrian', name: 'Piet Mondrian', aliases: ['mondrian'], difficulty: 'medium', era: '20th century', field: 'Painting', region: 'Netherlands' },
  { id: 'kazimir-malevich', name: 'Kazimir Malevich', aliases: ['malevich'], difficulty: 'medium', era: '20th century', field: 'Painting', region: 'Russia' },

  // --- Composers (10) ---
  { id: 'richard-strauss', name: 'Richard Strauss', aliases: ['richard strauss'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'Germany' },
  { id: 'felix-mendelssohn', name: 'Felix Mendelssohn', aliases: ['mendelssohn'], difficulty: 'medium', era: '19th century', field: 'Music', region: 'Germany' },
  { id: 'robert-schumann', name: 'Robert Schumann', aliases: ['schumann'], difficulty: 'medium', era: '19th century', field: 'Music', region: 'Germany' },
  { id: 'sergei-rachmaninoff', name: 'Sergei Rachmaninoff', aliases: ['rachmaninoff', 'rachmaninov'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'Russia' },
  { id: 'antonin-dvorak', name: 'Antonín Dvořák', aliases: ['dvorak', 'dvořák'], difficulty: 'medium', era: '19th century', field: 'Music', region: 'Czech Republic' },
  { id: 'modest-mussorgsky', name: 'Modest Mussorgsky', aliases: ['mussorgsky'], difficulty: 'medium', era: '19th century', field: 'Music', region: 'Russia' },
  { id: 'sergei-prokofiev', name: 'Sergei Prokofiev', aliases: ['prokofiev'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'Russia' },
  { id: 'dmitri-shostakovich', name: 'Dmitri Shostakovich', aliases: ['shostakovich'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'Russia' },
  { id: 'aaron-copland', name: 'Aaron Copland', aliases: ['copland'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'USA' },
  { id: 'george-gershwin', name: 'George Gershwin', aliases: ['gershwin'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'USA' },

  // --- Writers (20) ---
  { id: 'james-baldwin', name: 'James Baldwin', aliases: ['baldwin'], wikipediaTitle: 'James Baldwin', difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'toni-morrison', name: 'Toni Morrison', aliases: ['morrison'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'maya-angelou', name: 'Maya Angelou', aliases: ['angelou'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'langston-hughes', name: 'Langston Hughes', aliases: ['langston hughes'], difficulty: 'medium', era: '20th century', field: 'Poetry', region: 'USA' },
  { id: 'zora-neale-hurston', name: 'Zora Neale Hurston', aliases: ['hurston'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'jorge-luis-borges', name: 'Jorge Luis Borges', aliases: ['borges'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Argentina' },
  { id: 'pablo-neruda', name: 'Pablo Neruda', aliases: ['neruda'], difficulty: 'medium', era: '20th century', field: 'Poetry', region: 'Chile' },
  { id: 'octavio-paz', name: 'Octavio Paz', aliases: ['paz'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Mexico' },
  { id: 'samuel-beckett', name: 'Samuel Beckett', aliases: ['beckett'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Ireland' },
  { id: 'tennessee-williams', name: 'Tennessee Williams', aliases: ['tennessee williams'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'arthur-miller', name: 'Arthur Miller', aliases: ['arthur miller'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'eugene-oneill', name: "Eugene O'Neill", aliases: ['oneill', "o'neill"], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA' },
  { id: 'george-bernard-shaw', name: 'George Bernard Shaw', aliases: ['shaw', 'gb shaw'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Ireland' },
  { id: 'henrik-ibsen', name: 'Henrik Ibsen', aliases: ['ibsen'], difficulty: 'medium', era: '19th century', field: 'Literature', region: 'Norway' },
  { id: 'anton-chekhov', name: 'Anton Chekhov', aliases: ['chekhov'], difficulty: 'medium', era: '19th century', field: 'Literature', region: 'Russia' },
  { id: 'nikolai-gogol', name: 'Nikolai Gogol', aliases: ['gogol'], difficulty: 'medium', era: '19th century', field: 'Literature', region: 'Russia' },
  { id: 'alexander-pushkin', name: 'Alexander Pushkin', aliases: ['pushkin'], difficulty: 'medium', era: '19th century', field: 'Poetry', region: 'Russia' },
  { id: 'ivan-turgenev', name: 'Ivan Turgenev', aliases: ['turgenev'], difficulty: 'medium', era: '19th century', field: 'Literature', region: 'Russia' },
  { id: 'thomas-mann', name: 'Thomas Mann', aliases: ['thomas mann'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Germany' },
  { id: 'hermann-hesse', name: 'Hermann Hesse', aliases: ['hesse'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'Germany / Switzerland' },

  // --- Leaders (15) ---
  { id: 'maximilien-robespierre', name: 'Maximilien Robespierre', aliases: ['robespierre'], difficulty: 'medium', era: '18th century', field: 'Politics', region: 'France' },
  { id: 'georges-danton', name: 'Georges Danton', aliases: ['danton'], difficulty: 'medium', era: '18th century', field: 'Politics', region: 'France' },
  { id: 'cardinal-richelieu', name: 'Cardinal Richelieu', aliases: ['richelieu'], difficulty: 'medium', era: '17th century', field: 'Politics', region: 'France' },
  { id: 'oliver-cromwell', name: 'Oliver Cromwell', aliases: ['cromwell'], difficulty: 'medium', era: '17th century', field: 'Politics', region: 'England' },
  { id: 'william-pitt-younger', name: 'William Pitt the Younger', aliases: ['pitt', 'william pitt'], difficulty: 'medium', era: '18th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'benjamin-disraeli', name: 'Benjamin Disraeli', aliases: ['disraeli'], difficulty: 'medium', era: '19th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'william-gladstone', name: 'William Ewart Gladstone', aliases: ['gladstone'], wikipediaTitle: 'William Ewart Gladstone', difficulty: 'medium', era: '19th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'david-lloyd-george', name: 'David Lloyd George', aliases: ['lloyd george'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'neville-chamberlain', name: 'Neville Chamberlain', aliases: ['chamberlain'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'United Kingdom' },
  { id: 'haile-selassie', name: 'Haile Selassie', aliases: ['selassie'], difficulty: 'medium', era: '20th century', field: 'Royalty', region: 'Ethiopia' },
  { id: 'kwame-nkrumah', name: 'Kwame Nkrumah', aliases: ['nkrumah'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'Ghana' },
  { id: 'jomo-kenyatta', name: 'Jomo Kenyatta', aliases: ['kenyatta'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'Kenya' },
  { id: 'patrice-lumumba', name: 'Patrice Lumumba', aliases: ['lumumba'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'DR Congo' },
  { id: 'josip-broz-tito', name: 'Josip Broz Tito', aliases: ['tito'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'Yugoslavia' },
  { id: 'francisco-franco', name: 'Francisco Franco', aliases: ['franco'], difficulty: 'medium', era: '20th century', field: 'Politics', region: 'Spain' },

  // --- Philosophers (10) ---
  { id: 'arthur-schopenhauer', name: 'Arthur Schopenhauer', aliases: ['schopenhauer'], difficulty: 'medium', era: '19th century', field: 'Philosophy', region: 'Germany' },
  { id: 'baruch-spinoza', name: 'Baruch Spinoza', aliases: ['spinoza'], difficulty: 'medium', era: '17th century', field: 'Philosophy', region: 'Netherlands' },
  { id: 'gottfried-leibniz', name: 'Gottfried Wilhelm Leibniz', aliases: ['leibniz'], difficulty: 'medium', era: '17th century', field: 'Philosophy', region: 'Germany' },
  { id: 'thomas-hobbes', name: 'Thomas Hobbes', aliases: ['hobbes'], difficulty: 'medium', era: '17th century', field: 'Philosophy', region: 'United Kingdom' },
  { id: 'denis-diderot', name: 'Denis Diderot', aliases: ['diderot'], difficulty: 'medium', era: '18th century', field: 'Philosophy', region: 'France' },
  { id: 'adam-smith', name: 'Adam Smith', aliases: ['adam smith'], difficulty: 'medium', era: '18th century', field: 'Economics', region: 'Scotland' },
  { id: 'john-dewey', name: 'John Dewey', aliases: ['dewey'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'USA' },
  { id: 'william-james', name: 'William James', aliases: ['william james'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'USA' },
  { id: 'bertrand-russell', name: 'Bertrand Russell', aliases: ['russell'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'United Kingdom' },
  { id: 'ludwig-wittgenstein', name: 'Ludwig Wittgenstein', aliases: ['wittgenstein'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'Austria / UK' },

  // --- Religious (5) ---
  { id: 'john-calvin', name: 'John Calvin', aliases: ['calvin'], difficulty: 'medium', era: '16th century', field: 'Religion', region: 'France / Switzerland' },
  { id: 'john-wesley', name: 'John Wesley', aliases: ['wesley'], difficulty: 'medium', era: '18th century', field: 'Religion', region: 'United Kingdom' },
  { id: 'huldrych-zwingli', name: 'Huldrych Zwingli', aliases: ['zwingli'], difficulty: 'medium', era: '16th century', field: 'Religion', region: 'Switzerland' },
  { id: 'thomas-becket', name: 'Thomas Becket', aliases: ['becket'], difficulty: 'medium', era: '12th century', field: 'Religion', region: 'England' },
  { id: 'meister-eckhart', name: 'Meister Eckhart', aliases: ['eckhart'], difficulty: 'medium', era: '14th century', field: 'Religion', region: 'Germany' },

  // --- Activists (5) ---
  { id: 'web-du-bois', name: 'W. E. B. Du Bois', aliases: ['du bois'], wikipediaTitle: 'W. E. B. Du Bois', difficulty: 'medium', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'booker-t-washington', name: 'Booker T. Washington', aliases: ['booker washington'], wikipediaTitle: 'Booker T. Washington', difficulty: 'medium', era: '20th century', field: 'Activism', region: 'USA' },
  { id: 'marcus-garvey', name: 'Marcus Garvey', aliases: ['garvey'], difficulty: 'medium', era: '20th century', field: 'Activism', region: 'Jamaica' },
  { id: 'simone-weil', name: 'Simone Weil', aliases: ['weil'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'France' },
  { id: 'thurgood-marshall', name: 'Thurgood Marshall', aliases: ['marshall'], difficulty: 'medium', era: '20th century', field: 'Law', region: 'USA' },

  // --- Athletes (5) ---
  { id: 'muhammad-ali', name: 'Muhammad Ali', aliases: ['ali'], difficulty: 'medium', era: '20th century', field: 'Boxing', region: 'USA' },
  { id: 'pele', name: 'Pelé', aliases: ['pele'], difficulty: 'medium', era: '20th century', field: 'Football', region: 'Brazil' },
  { id: 'babe-ruth', name: 'Babe Ruth', aliases: ['babe ruth'], difficulty: 'medium', era: '20th century', field: 'Baseball', region: 'USA' },
  { id: 'jesse-owens', name: 'Jesse Owens', aliases: ['owens'], difficulty: 'medium', era: '20th century', field: 'Athletics', region: 'USA' },
  { id: 'jackie-robinson', name: 'Jackie Robinson', aliases: ['jackie robinson'], difficulty: 'medium', era: '20th century', field: 'Baseball', region: 'USA' },

  // --- Explorers (5) ---
  { id: 'ferdinand-magellan', name: 'Ferdinand Magellan', aliases: ['magellan'], difficulty: 'medium', era: '16th century', field: 'Exploration', region: 'Portugal' },
  { id: 'vasco-da-gama', name: 'Vasco da Gama', aliases: ['da gama'], difficulty: 'medium', era: '15th century', field: 'Exploration', region: 'Portugal' },
  { id: 'james-cook', name: 'James Cook', aliases: ['captain cook'], difficulty: 'medium', era: '18th century', field: 'Exploration', region: 'United Kingdom' },
  { id: 'ernest-shackleton', name: 'Ernest Shackleton', aliases: ['shackleton'], difficulty: 'medium', era: '20th century', field: 'Exploration', region: 'United Kingdom' },
  { id: 'roald-amundsen', name: 'Roald Amundsen', aliases: ['amundsen'], difficulty: 'medium', era: '20th century', field: 'Exploration', region: 'Norway' },

  // --- Other notable (5) ---
  { id: 'rudyard-kipling', name: 'Rudyard Kipling', aliases: ['kipling'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'United Kingdom' },
  { id: 'edith-piaf', name: 'Édith Piaf', aliases: ['piaf'], difficulty: 'medium', era: '20th century', field: 'Music', region: 'France' },
  { id: 'gertrude-stein', name: 'Gertrude Stein', aliases: ['stein'], difficulty: 'medium', era: '20th century', field: 'Literature', region: 'USA / France' },
  { id: 'walter-benjamin', name: 'Walter Benjamin', aliases: ['benjamin'], difficulty: 'medium', era: '20th century', field: 'Philosophy', region: 'Germany' },
  { id: 'hg-wells', name: 'H. G. Wells', aliases: ['hg wells'], wikipediaTitle: 'H. G. Wells', difficulty: 'medium', era: '20th century', field: 'Literature', region: 'United Kingdom' },

  // ==========================================================================
  // HARD — obscure but real (~81)
  // ==========================================================================

  // --- Ancient (15) ---
  { id: 'thucydides', name: 'Thucydides', aliases: ['thucydides'], difficulty: 'hard', era: 'Ancient', field: 'History', region: 'Greece' },
  { id: 'herodotus', name: 'Herodotus', aliases: ['herodotus'], difficulty: 'hard', era: 'Ancient', field: 'History', region: 'Greece' },
  { id: 'pericles', name: 'Pericles', aliases: ['pericles'], difficulty: 'hard', era: 'Ancient', field: 'Politics', region: 'Greece' },
  { id: 'alcibiades', name: 'Alcibiades', aliases: ['alcibiades'], difficulty: 'hard', era: 'Ancient', field: 'Military', region: 'Greece' },
  { id: 'leonidas-i', name: 'Leonidas I', aliases: ['leonidas'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Sparta' },
  { id: 'cyrus-the-great', name: 'Cyrus the Great', aliases: ['cyrus'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Persia' },
  { id: 'darius-the-great', name: 'Darius the Great', aliases: ['darius', 'darius i'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Persia' },
  { id: 'xerxes-i', name: 'Xerxes I', aliases: ['xerxes'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Persia' },
  { id: 'spartacus', name: 'Spartacus', aliases: ['spartacus'], difficulty: 'hard', era: 'Ancient', field: 'Military', region: 'Roman Empire' },
  { id: 'caligula', name: 'Caligula', aliases: ['caligula'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Roman Empire' },
  { id: 'nero', name: 'Nero', aliases: ['nero'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'Roman Empire' },
  { id: 'marcus-aurelius', name: 'Marcus Aurelius', aliases: ['marcus aurelius'], difficulty: 'hard', era: 'Ancient', field: 'Philosophy', region: 'Roman Empire' },
  { id: 'epicurus', name: 'Epicurus', aliases: ['epicurus'], difficulty: 'hard', era: 'Ancient', field: 'Philosophy', region: 'Greece' },
  { id: 'epictetus', name: 'Epictetus', aliases: ['epictetus'], difficulty: 'hard', era: 'Ancient', field: 'Philosophy', region: 'Greece' },
  { id: 'seneca-younger', name: 'Seneca the Younger', aliases: ['seneca'], difficulty: 'hard', era: 'Ancient', field: 'Philosophy', region: 'Roman Empire' },

  // --- Medieval (16) ---
  { id: 'saladin', name: 'Saladin', aliases: ['saladin'], difficulty: 'hard', era: '12th century', field: 'Military', region: 'Egypt / Syria' },
  { id: 'richard-i', name: 'Richard I of England', aliases: ['richard the lionheart'], wikipediaTitle: 'Richard I of England', difficulty: 'hard', era: '12th century', field: 'Royalty', region: 'England' },
  { id: 'frederick-barbarossa', name: 'Frederick Barbarossa', aliases: ['barbarossa'], difficulty: 'hard', era: '12th century', field: 'Royalty', region: 'Holy Roman Empire' },
  { id: 'baldwin-iv-jerusalem', name: 'Baldwin IV of Jerusalem', aliases: ['baldwin iv'], difficulty: 'hard', era: '12th century', field: 'Royalty', region: 'Jerusalem' },
  { id: 'william-of-ockham', name: 'William of Ockham', aliases: ['ockham', 'occam'], difficulty: 'hard', era: '14th century', field: 'Philosophy', region: 'England' },
  { id: 'roger-bacon', name: 'Roger Bacon', aliases: ['roger bacon'], difficulty: 'hard', era: '13th century', field: 'Philosophy', region: 'England' },
  { id: 'duns-scotus', name: 'Duns Scotus', aliases: ['duns scotus'], difficulty: 'hard', era: '14th century', field: 'Philosophy', region: 'Scotland' },
  { id: 'peter-abelard', name: 'Peter Abelard', aliases: ['abelard'], difficulty: 'hard', era: '12th century', field: 'Philosophy', region: 'France' },
  { id: 'heloise', name: 'Héloïse', aliases: ['heloise'], wikipediaTitle: 'Héloïse', difficulty: 'hard', era: '12th century', field: 'Religion', region: 'France' },
  { id: 'matilda-of-tuscany', name: 'Matilda of Tuscany', aliases: ['matilda'], difficulty: 'hard', era: '11th century', field: 'Royalty', region: 'Italy' },
  { id: 'christine-de-pizan', name: 'Christine de Pizan', aliases: ['de pizan'], difficulty: 'hard', era: '15th century', field: 'Literature', region: 'France' },
  { id: 'francois-villon', name: 'François Villon', aliases: ['villon'], difficulty: 'hard', era: '15th century', field: 'Poetry', region: 'France' },
  { id: 'geoffrey-chaucer', name: 'Geoffrey Chaucer', aliases: ['chaucer'], difficulty: 'hard', era: '14th century', field: 'Literature', region: 'England' },
  { id: 'thomas-more', name: 'Thomas More', aliases: ['more'], difficulty: 'hard', era: '16th century', field: 'Politics', region: 'England' },
  { id: 'robert-the-bruce', name: 'Robert the Bruce', aliases: ['robert bruce'], difficulty: 'hard', era: '14th century', field: 'Royalty', region: 'Scotland' },
  { id: 'thomas-cromwell', name: 'Thomas Cromwell', aliases: ['thomas cromwell'], difficulty: 'hard', era: '16th century', field: 'Politics', region: 'England' },

  // --- Polymaths & scientists (15) ---
  { id: 'omar-khayyam', name: 'Omar Khayyam', aliases: ['khayyam'], difficulty: 'hard', era: '12th century', field: 'Mathematics', region: 'Persia' },
  { id: 'ibn-battuta', name: 'Ibn Battuta', aliases: ['ibn battuta'], difficulty: 'hard', era: '14th century', field: 'Exploration', region: 'Morocco' },
  { id: 'ibn-khaldun', name: 'Ibn Khaldun', aliases: ['ibn khaldun'], difficulty: 'hard', era: '14th century', field: 'History', region: 'Tunisia' },
  { id: 'averroes', name: 'Averroes', aliases: ['ibn rushd'], difficulty: 'hard', era: '12th century', field: 'Philosophy', region: 'Al-Andalus' },
  { id: 'ibn-al-haytham', name: 'Ibn al-Haytham', aliases: ['alhazen'], difficulty: 'hard', era: '11th century', field: 'Physics', region: 'Iraq' },
  { id: 'jabir-ibn-hayyan', name: 'Jabir ibn Hayyan', aliases: ['geber'], difficulty: 'hard', era: '8th century', field: 'Chemistry', region: 'Persia' },
  { id: 'paracelsus', name: 'Paracelsus', aliases: ['paracelsus'], difficulty: 'hard', era: '16th century', field: 'Medicine', region: 'Switzerland' },
  { id: 'andreas-vesalius', name: 'Andreas Vesalius', aliases: ['vesalius'], difficulty: 'hard', era: '16th century', field: 'Anatomy', region: 'Belgium' },
  { id: 'william-harvey', name: 'William Harvey', aliases: ['harvey'], difficulty: 'hard', era: '17th century', field: 'Medicine', region: 'United Kingdom' },
  { id: 'tycho-brahe', name: 'Tycho Brahe', aliases: ['brahe'], difficulty: 'hard', era: '16th century', field: 'Astronomy', region: 'Denmark' },
  { id: 'georg-cantor', name: 'Georg Cantor', aliases: ['cantor'], difficulty: 'hard', era: '19th century', field: 'Mathematics', region: 'Germany' },
  { id: 'emmy-noether', name: 'Emmy Noether', aliases: ['noether'], difficulty: 'hard', era: '20th century', field: 'Mathematics', region: 'Germany' },
  { id: 'nikolai-lobachevsky', name: 'Nikolai Lobachevsky', aliases: ['lobachevsky'], difficulty: 'hard', era: '19th century', field: 'Mathematics', region: 'Russia' },
  { id: 'henri-poincare', name: 'Henri Poincaré', aliases: ['poincare', 'poincaré'], difficulty: 'hard', era: '20th century', field: 'Mathematics', region: 'France' },
  { id: 'kurt-godel', name: 'Kurt Gödel', aliases: ['godel', 'gödel'], difficulty: 'hard', era: '20th century', field: 'Mathematics', region: 'Austria / USA' },

  // --- Lesser-known leaders (15) ---
  { id: 'ashoka', name: 'Ashoka', aliases: ['ashoka'], difficulty: 'hard', era: 'Ancient', field: 'Royalty', region: 'India' },
  { id: 'akbar', name: 'Akbar', aliases: ['akbar'], difficulty: 'hard', era: '16th century', field: 'Royalty', region: 'India' },
  { id: 'aurangzeb', name: 'Aurangzeb', aliases: ['aurangzeb'], difficulty: 'hard', era: '17th century', field: 'Royalty', region: 'India' },
  { id: 'timur', name: 'Timur', aliases: ['tamerlane'], difficulty: 'hard', era: '14th century', field: 'Royalty', region: 'Central Asia' },
  { id: 'mehmed-ii', name: 'Mehmed II', aliases: ['mehmed'], difficulty: 'hard', era: '15th century', field: 'Royalty', region: 'Ottoman Empire' },
  { id: 'kublai-khan', name: 'Kublai Khan', aliases: ['kublai'], difficulty: 'hard', era: '13th century', field: 'Royalty', region: 'Mongol Empire' },
  { id: 'wu-zetian', name: 'Wu Zetian', aliases: ['wu zetian'], difficulty: 'hard', era: '7th century', field: 'Royalty', region: 'China' },
  { id: 'kangxi-emperor', name: 'Kangxi Emperor', aliases: ['kangxi'], difficulty: 'hard', era: '17th century', field: 'Royalty', region: 'China' },
  { id: 'qianlong-emperor', name: 'Qianlong Emperor', aliases: ['qianlong'], difficulty: 'hard', era: '18th century', field: 'Royalty', region: 'China' },
  { id: 'tokugawa-ieyasu', name: 'Tokugawa Ieyasu', aliases: ['tokugawa'], difficulty: 'hard', era: '17th century', field: 'Royalty', region: 'Japan' },
  { id: 'oda-nobunaga', name: 'Oda Nobunaga', aliases: ['nobunaga'], difficulty: 'hard', era: '16th century', field: 'Royalty', region: 'Japan' },
  { id: 'toyotomi-hideyoshi', name: 'Toyotomi Hideyoshi', aliases: ['hideyoshi'], difficulty: 'hard', era: '16th century', field: 'Royalty', region: 'Japan' },
  { id: 'menelik-ii', name: 'Menelik II', aliases: ['menelik'], difficulty: 'hard', era: '20th century', field: 'Royalty', region: 'Ethiopia' },
  { id: 'cetshwayo', name: 'Cetshwayo', aliases: ['cetshwayo'], difficulty: 'hard', era: '19th century', field: 'Royalty', region: 'South Africa' },
  { id: 'tecumseh', name: 'Tecumseh', aliases: ['tecumseh'], difficulty: 'hard', era: '19th century', field: 'Military', region: 'North America' },

  // --- Mystics & spiritual (10) ---
  { id: 'rumi', name: 'Rumi', aliases: ['rumi'], difficulty: 'hard', era: '13th century', field: 'Poetry', region: 'Persia' },
  { id: 'teresa-of-avila', name: 'Teresa of Ávila', aliases: ['teresa de avila'], difficulty: 'hard', era: '16th century', field: 'Religion', region: 'Spain' },
  { id: 'john-of-the-cross', name: 'John of the Cross', aliases: ['john of the cross'], difficulty: 'hard', era: '16th century', field: 'Religion', region: 'Spain' },
  { id: 'julian-of-norwich', name: 'Julian of Norwich', aliases: ['julian of norwich'], difficulty: 'hard', era: '14th century', field: 'Religion', region: 'England' },
  { id: 'catherine-of-siena', name: 'Catherine of Siena', aliases: ['catherine siena'], difficulty: 'hard', era: '14th century', field: 'Religion', region: 'Italy' },
  { id: 'thomas-merton', name: 'Thomas Merton', aliases: ['merton'], difficulty: 'hard', era: '20th century', field: 'Religion', region: 'USA' },
  { id: 'paramahansa-yogananda', name: 'Paramahansa Yogananda', aliases: ['yogananda'], difficulty: 'hard', era: '20th century', field: 'Religion', region: 'India / USA' },
  { id: 'swami-vivekananda', name: 'Swami Vivekananda', aliases: ['vivekananda'], difficulty: 'hard', era: '19th century', field: 'Religion', region: 'India' },
  { id: 'ramakrishna', name: 'Ramakrishna', aliases: ['ramakrishna'], difficulty: 'hard', era: '19th century', field: 'Religion', region: 'India' },
  { id: 'al-ghazali', name: 'Al-Ghazali', aliases: ['ghazali'], difficulty: 'hard', era: '12th century', field: 'Philosophy', region: 'Persia' },

  // --- Pre-modern artists (10) ---
  { id: 'giotto', name: 'Giotto', aliases: ['giotto di bondone'], wikipediaTitle: 'Giotto', difficulty: 'hard', era: '14th century', field: 'Painting', region: 'Italy' },
  { id: 'cimabue', name: 'Cimabue', aliases: ['cimabue'], difficulty: 'hard', era: '13th century', field: 'Painting', region: 'Italy' },
  { id: 'fra-angelico', name: 'Fra Angelico', aliases: ['fra angelico'], difficulty: 'hard', era: '15th century', field: 'Painting', region: 'Italy' },
  { id: 'donatello', name: 'Donatello', aliases: ['donatello'], difficulty: 'hard', era: '15th century', field: 'Sculpture', region: 'Italy' },
  { id: 'masaccio', name: 'Masaccio', aliases: ['masaccio'], difficulty: 'hard', era: '15th century', field: 'Painting', region: 'Italy' },
  { id: 'jan-van-eyck', name: 'Jan van Eyck', aliases: ['van eyck'], difficulty: 'hard', era: '15th century', field: 'Painting', region: 'Belgium' },
  { id: 'albrecht-durer', name: 'Albrecht Dürer', aliases: ['durer', 'dürer'], difficulty: 'hard', era: '16th century', field: 'Painting', region: 'Germany' },
  { id: 'mary-cassatt', name: 'Mary Cassatt', aliases: ['cassatt'], difficulty: 'hard', era: '20th century', field: 'Painting', region: 'USA' },
  { id: 'artemisia-gentileschi', name: 'Artemisia Gentileschi', aliases: ['gentileschi'], difficulty: 'hard', era: '17th century', field: 'Painting', region: 'Italy' },
  { id: 'sofonisba-anguissola', name: 'Sofonisba Anguissola', aliases: ['anguissola'], difficulty: 'hard', era: '16th century', field: 'Painting', region: 'Italy' },
];

export default SEED;
